-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 14, 2025 at 05:15 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bakery_recipes`
--

-- --------------------------------------------------------

--
-- Table structure for table `recipes`
--

CREATE TABLE `recipes` (
  `id` int(11) NOT NULL,
  `nama_resep` varchar(100) NOT NULL,
  `kategori` varchar(50) NOT NULL,
  `alat` text NOT NULL,
  `bahan` text NOT NULL,
  `langkah` text NOT NULL,
  `gambar` varchar(500) DEFAULT NULL,
  `tingkat_kesulitan` varchar(20) NOT NULL,
  `waktu` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `recipes`
--

INSERT INTO `recipes` (`id`, `nama_resep`, `kategori`, `alat`, `bahan`, `langkah`, `gambar`, `tingkat_kesulitan`, `waktu`) VALUES
(1, 'White Bread', 'Bread', 'Oven, Loyang loaf, Mixer, Mangkuk besar', '500g tepung terigu protein tinggi, 300ml air hangat, 7g ragi instan, 30g gula, 30g mentega, 10g garam', '1. Campur tepung, gula, garam, dan ragi.\n   2. Tambahkan air hangat sedikit demi sedikit.\n   3. Uleni hingga kalis.\n   4. Masukkan mentega, uleni lagi 10 menit.\n   5. Diamkan adonan 1 jam hingga mengembang.\n   6. Bentuk loaf, taruh di loyang.\n   7. Diamkan lagi 30 menit.\n   8. Panggang 180C selama 35 menit.\n   9. Dinginkan sebelum dipotong.', 'https://plus.unsplash.com/premium_photo-1695084221473-1fb5b365bbb3?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8d2hpdGUlMjBicmVhZHxlbnwwfHwwfHx8MA%3D%3D', 'Mudah', '2 jam'),
(2, 'Whole Wheat Bread', 'Bread', 'Oven, Loyang loaf, Mixer, Mangkuk besar', '400g tepung gandum utuh, 100g tepung terigu, 300ml air hangat, 7g ragi instan, 20g madu, 20g minyak zaitun, 10g garam', '1. Campur tepung gandum, tepung terigu, garam, dan ragi.\r\n   2. Tambahkan air hangat, madu, dan minyak zaitun.\r\n   3. Uleni hingga kalis.\r\n   4. Diamkan 1 jam hingga mengembang.\r\n   5. Bentuk loaf, taruh di loyang.\r\n   6. Diamkan lagi 30 menit.\r\n   7. Panggang 180C selama 40 menit.\r\n   8. Dinginkan sebelum disajikan.', 'https://plus.unsplash.com/premium_photo-1726761713380-59275b2dc2c5?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8d2hvbGUlMjB3aGVhdCUyMGJyZWFkfGVufDB8MHwwfHx8MA%3D%3D', 'Sedang', '2 jam'),
(3, 'Oat Bread', 'Bread', 'Oven, Loyang loaf, Mixer, Mangkuk besar', '300g tepung terigu, 200g oat, 250ml susu hangat, 7g ragi instan, 30g madu, 30g mentega, 10g garam', '1. Campur tepung, oat, garam, dan ragi.\r\n   2. Tambahkan susu hangat dan madu.\r\n   3. Uleni hingga kalis.\r\n   4. Masukkan mentega, uleni lagi.\r\n   5. Diamkan 1 jam hingga mengembang.\r\n   6. Bentuk loaf, taburi oat di atasnya.\r\n   7. Diamkan lagi 30 menit.\r\n   8. Panggang 180C selama 35 menit.\r\n   9. Dinginkan sebelum dipotong.', 'https://plus.unsplash.com/premium_photo-1661770191552-90e12a9c41aa?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzN8fG9hdCUyMGJyZWFkfGVufDB8MHwwfHx8MA%3D%3D', 'Sedang', '2 jam'),
(4, 'Rye Bread', 'Bread', 'Oven, Loyang loaf, Mixer, Mangkuk besar', '300g tepung rye, 200g tepung terigu, 300ml air hangat, 7g ragi instan, 20g molasses, 10g garam', '1. Campur tepung rye, tepung terigu, garam, dan ragi.\r\n   2. Tambahkan air hangat dan molasses.\r\n   3. Uleni hingga kalis.\r\n   4. Diamkan 1 jam hingga mengembang.\r\n   5. Bentuk loaf, taruh di loyang.\r\n   6. Diamkan lagi 30 menit.\r\n   7. Panggang 180C selama 40 menit.\r\n   8. Dinginkan sebelum dipotong.', 'https://th.bing.com/th/id/OIP.eS6uuQTN2UVXBrlYPQVg4QHaD4?w=327&h=180&c=7&r=0&o=7&cb=ucfimg2&dpr=1.4&pid=1.7&rm=3&ucfimg=1', 'Sulit', '2.5 jam'),
(5, 'Sourdough Bread', 'Bread', 'Oven, Dutch oven, Mangkuk besar, Spatula', '400g tepung terigu, 100g starter sourdough aktif, 300ml air, 10g garam', '1. Campur tepung dan air, diamkan 30 menit (autolyse).\r\n   2. Tambahkan starter sourdough aktif, aduk rata.\r\n   3. Masukkan garam, aduk perlahan.\r\n   4. Diamkan adonan 30 menit.\r\n   5. Lakukan lipatan pertama (stretch & fold).\r\n   6. Diamkan 30 menit lagi.\r\n   7. Lakukan lipatan kedua.\r\n   8. Diamkan 30 menit lagi.\r\n   9. Lakukan lipatan ketiga.\r\n   10. Fermentasi bulk 4–6 jam hingga mengembang 2x lipat.\r\n   11. Bentuk bulat, diamkan 1 jam (proofing).\r\n   12. Panaskan oven dengan dutch oven.\r\n   13. Panggang 230C 20 menit dengan tutup.\r\n   14. Buka tutup, panggang lagi 20 menit.\r\n   15. Dinginkan minimal 1 jam sebelum dipotong.', 'https://plus.unsplash.com/premium_photo-1700767185782-47a987a495df?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8c291cmRvdWdoJTIwYnJlYWR8ZW58MHwwfDB8fHww', 'Sulit', '6 jam'),
(6, 'Brioche', 'Bread', 'Oven, Mixer, Loyang loaf, Mangkuk besar, Spatula', '500g tepung terigu protein tinggi, 60g gula, 7g ragi instan, 5 butir telur, 250g butter, 10g garam, 100ml susu', '1. Campur tepung, gula, garam, dan ragi.\r\n   2. Tambahkan susu dan telur satu per satu, aduk rata.\r\n   3. Masukkan butter potong kecil, uleni hingga adonan elastis.\r\n   4. Diamkan adonan 1 jam hingga mengembang.\r\n   5. Keluarkan udara dari adonan, diamkan lagi 1 jam di kulkas.\r\n   6. Bentuk loaf atau bulatan kecil sesuai selera.\r\n   7. Proofing 45 menit hingga mengembang.\r\n   8. Oles permukaan dengan telur.\r\n   9. Panggang 180C selama 30–35 menit.\r\n   10. Dinginkan sebelum disajikan.', 'https://www.quelquesgrammesdegourmandise.com/wp-content/uploads/2021/03/brioche-nanterre-thermomix-qgdg.jpg', 'Sulit', '3 jam'),
(7, 'Focaccia', 'Bread', 'Oven, Loyang datar, Mangkuk besar, Spatula, Mixer', '500g tepung terigu, 350ml air hangat, 7g ragi instan, 50ml minyak zaitun, 10g garam, rosemary segar, tomat ceri', '1. Campur tepung, garam, dan ragi.\r\n   2. Tambahkan air hangat dan minyak zaitun, aduk rata.\r\n   3. Uleni hingga adonan elastis.\r\n   4. Diamkan 1 jam hingga mengembang.\r\n   5. Tuang adonan ke loyang datar, ratakan.\r\n   6. Diamkan lagi 30 menit.\r\n   7. Tekan permukaan dengan jari untuk membuat lubang kecil.\r\n   8. Taburi rosemary dan tomat ceri.\r\n   9. Siram sedikit minyak zaitun di atasnya.\r\n   10. Panggang 200C selama 25 menit.\r\n   11. Dinginkan sebelum dipotong.', 'https://th.bing.com/th/id/OIP.gduIvbqrnn9RP_d6N-YckgHaE7?o=7&cb=ucfimg2&rm=3&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3', 'Sedang', '2 jam'),
(8, 'Ciabatta', 'Bread', 'Oven, Loyang datar, Mangkuk besar, Mixer, Spatula', '500g tepung terigu protein tinggi, 400ml air dingin, 7g ragi instan, 10g garam, 30ml minyak zaitun', '1. Campur tepung, garam, dan ragi.\r\n   2. Tambahkan air dingin dan minyak zaitun, aduk hingga adonan lengket.\r\n   3. Diamkan 1 jam, lakukan lipatan ringan.\r\n   4. Diamkan lagi 1 jam hingga adonan mengembang.\r\n   5. Tuang adonan ke loyang datar, bentuk memanjang.\r\n   6. Proofing 30 menit.\r\n   7. Panaskan oven 220C.\r\n   8. Panggang 25–30 menit hingga kulit kecoklatan.\r\n   9. Dinginkan sebelum dipotong.', 'https://tse2.mm.bing.net/th/id/OIP.KSGSxxpi06_s0v4zAubf3gHaE8?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3', 'Sedang', '3 jam'),
(9, 'Milk Bread', 'Bread', 'Oven, Loyang loaf, Mixer, Mangkuk besar', '500g tepung terigu, 250ml susu hangat, 50g gula, 7g ragi, 40g butter, 1 telur', '1. Campur tepung, gula, dan ragi\n2. Tambahkan susu hangat, aduk rata\n3. Masukkan telur dan butter\n4. Uleni hingga kalis\n5. Diamkan 1 jam hingga mengembang\n6. Kempiskan adonan, bentuk loaf\n7. Masukkan ke loyang dan diamkan lagi 30 menit\n8. Panggang 180°C selama 30 menit', 'https://tse2.mm.bing.net/th/id/OIP.ewe_PAb5TQ3xzzLsL8NyUQHaE7?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3', 'Mudah', '2 jam'),
(10, 'Potato Bread', 'Bread', 'Oven, Loyang loaf, Mangkuk besar, Penghalus kentang', '300g tepung terigu, 200g kentang rebus halus, 7g ragi, 200ml air, 10g garam', '1. Haluskan kentang rebus\n2. Campur tepung, kentang, dan ragi\n3. Tambahkan air dan garam\n4. Uleni hingga elastis\n5. Diamkan 1.5 jam hingga mengembang\n6. Kempiskan adonan, bentuk sesuai loyang\n7. Diamkan lagi 30 menit\n8. Panggang 190°C selama 35 menit\n9. Dinginkan sebelum dipotong', 'https://th.bing.com/th/id/OIP.ZUvT1k3pQDA7n5s0dfePxQHaE8?w=272&h=181&c=7&r=0&o=7&cb=ucfimg2&dpr=1.4&pid=1.7&rm=3&ucfimg=1', 'Sedang', '2.5 jam'),
(11, 'Honey Oat Bread', 'Bread', 'Oven, Loyang loaf, Mangkuk besar', '300g tepung terigu, 100g oat, 50g madu, 250ml air hangat, 7g ragi, 10g garam', '1. Rendam oat dengan air hangat 10 menit\n2. Campur tepung, madu, ragi, dan garam\n3. Tambahkan oat rendaman\n4. Uleni 10 menit\n5. Diamkan 1 jam hingga mengembang\n6. Kempiskan adonan, bentuk loaf\n7. Taburi oat di atasnya\n8. Diamkan lagi 30 menit\n9. Panggang 180°C selama 30–35 menit\n10. Dinginkan sebelum disajikan', 'https://th.bing.com/th/id/OIP.5iv0NGEqMrD2fk0dut8_AwHaE8?w=276&h=184&c=7&r=0&o=7&cb=ucfimg2&dpr=1.4&pid=1.7&rm=3&ucfimg=1', 'Sedang', '2 jam'),
(12, 'Garlic Herb Bread', 'Bread', 'Oven, Loyang datar, Mangkuk besar', '400g tepung terigu, 3 siung bawang putih cincang, 1 sdm rosemary, 250ml air, 7g ragi, 10g garam', '1. Tumis bawang putih sebentar\n2. Campur tepung, rosemary, dan ragi\n3. Tambahkan air dan bawang tumis\n4. Uleni hingga kalis\n5. Diamkan 1 jam\n6. Kempiskan adonan, bentuk pipih\n7. Letakkan di loyang dan diamkan lagi 20 menit\n8. Panggang 200°C selama 25 menit', 'https://th.bing.com/th/id/OIP._wI31Pqy6y5gViQDv0Z-nAHaE8?w=218&h=180&c=7&r=0&o=7&cb=ucfimg2&dpr=1.4&pid=1.7&rm=3&ucfimg=1', 'Sedang', '2 jam'),
(13, 'Multigrain Bread', 'Bread', 'Oven, Loyang loaf, Mangkuk besar', '200g tepung terigu, 100g tepung gandum, 50g biji-bijian campur, 250ml air, 7g ragi, 10g garam', '1. Campur semua tepung dan biji-bijian\n2. Tambahkan ragi dan garam\n3. Tuang air sedikit demi sedikit\n4. Uleni hingga kalis\n5. Diamkan 1 jam hingga mengembang\n6. Kempiskan adonan, bentuk loaf\n7. Masukkan ke loyang dan diamkan lagi 30 menit\n8. Panggang 180°C selama 40 menit\n9. Dinginkan sebelum dipotong', 'https://th.bing.com/th/id/OIP.eE0ry-xQSFwEq0pA1Nbm7QHaE8?w=248&h=180&c=7&r=0&o=7&cb=ucfimg2&dpr=1.4&pid=1.7&rm=3&ucfimg=1', 'Sulit', '2.5 jam'),
(14, 'Chocolate Cake', 'Cake', 'Oven, Mixer, Loyang bulat, Mangkuk besar', '200g tepung terigu, 150g gula, 50g kakao bubuk, 2 telur, 100ml susu, 100g butter, 1 sdt baking powder', '1. Campur tepung, kakao, dan baking powder\n2. Kocok telur dan gula hingga mengembang\n3. Tambahkan susu dan butter cair\n4. Masukkan campuran tepung sedikit demi sedikit\n5. Aduk rata hingga halus\n6. Tuang ke loyang bulat\n7. Panggang 180°C selama 35 menit\n8. Dinginkan sebelum dihias\n9. Sajikan dengan topping sesuai selera', 'https://i.pinimg.com/736x/b5/3c/a4/b53ca45d717c19cb3f6d5680e1ae1982.jpg', 'Sedang', '1.5 jam'),
(15, 'Cheesecake', 'Cake', 'Oven, Mixer, Loyang springform, Blender', '250g cream cheese, 100g gula, 2 telur, 100g biskuit, 50g butter, 100ml krim', '1. Hancurkan biskuit dengan blender\n2. Campur biskuit dengan butter cair\n3. Tekan ke dasar loyang springform\n4. Kocok cream cheese dan gula\n5. Tambahkan telur satu per satu\n6. Masukkan krim cair\n7. Aduk hingga halus\n8. Tuang ke loyang di atas base biskuit\n9. Panggang 160°C selama 45 menit\n10. Dinginkan sebelum disajikan', 'https://loving-newyork.com/wp-content/uploads/2023/07/Classic-New-York-Cheesecake-Recipe-1920x960.jpg', 'Sulit', '2 jam'),
(16, 'Red Velvet Cake', 'Cake', 'Oven, Mixer, Loyang bulat, Mangkuk besar', '200g tepung terigu, 150g gula, 2 telur, 100ml buttermilk, 100g butter, 1 sdt baking powder, pewarna merah', '1. Campur tepung dan baking powder\n2. Kocok telur dan gula hingga mengembang\n3. Tambahkan butter cair dan buttermilk\n4. Masukkan pewarna merah\n5. Aduk rata hingga halus\n6. Tuang ke loyang bulat\n7. Panggang 170°C selama 40 menit\n8. Dinginkan sebelum diberi frosting', 'https://th.bing.com/th/id/OIP.MxfLKJjmmrnr4gpyQ5M1cAHaE7?w=250&h=180&c=7&r=0&o=7&cb=ucfimg2&dpr=1.4&pid=1.7&rm=3&ucfimg=1', 'Sedang', '2 jam'),
(17, 'Carrot Cake', 'Cake', 'Oven, Mixer, Loyang loaf, Parutan', '200g tepung terigu, 150g gula, 2 telur, 100g wortel parut, 100ml minyak sayur, 1 sdt baking powder, 1 sdt kayu manis', '1. Parut wortel\n2. Campur tepung, baking powder, dan kayu manis\n3. Kocok telur dan gula\n4. Tambahkan minyak sayur\n5. Masukkan wortel parut\n6. Aduk rata hingga halus\n7. Tuang ke loyang loaf\n8. Panggang 180°C selama 40 menit\n9. Dinginkan sebelum disajikan', 'https://cakesmania.net/wp-content/uploads/carrot-cake.jpg', 'Sedang', '2 jam'),
(18, 'Sponge Cake', 'Cake', 'Oven, Mixer, Loyang bulat, Mangkuk besar', '200g tepung terigu, 150g gula, 4 telur, 50g butter, 1 sdt baking powder', '1. Kocok telur dan gula hingga mengembang\n2. Campur tepung dan baking powder\n3. Masukkan campuran tepung ke adonan telur\n4. Tambahkan butter cair\n5. Aduk perlahan hingga rata\n6. Tuang ke loyang bulat\n7. Panggang 180°C selama 30 menit\n8. Dinginkan sebelum dipotong', 'https://piya.me/wp-content/uploads/2025/04/victoria-sponge-cake-1.jpg', 'Mudah', '1.5 jam'),
(19, 'Chocolate Chip Cookies', 'Cookies', 'Oven, Mixer, Loyang datar, Spatula', '200g tepung terigu, 100g gula, 100g brown sugar, 100g butter, 1 telur, 100g chocolate chips, 1 sdt baking soda', '1. Campur tepung dan baking soda\n2. Kocok butter, gula pasir, dan brown sugar\n3. Tambahkan telur\n4. Masukkan campuran tepung sedikit demi sedikit\n5. Aduk rata\n6. Tambahkan chocolate chips\n7. Bentuk bulat kecil di loyang\n8. Panggang 180°C selama 12 menit\n9. Dinginkan sebelum disajikan', 'https://tse2.mm.bing.net/th/id/OIP.N2Dvmwqf5dqz6Yvp691yWQAAAA?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3', 'Mudah', '45 menit'),
(20, 'Oatmeal Raisin Cookies', 'Cookies', 'Oven, Mixer, Loyang datar, Mangkuk besar', '150g oat, 100g tepung terigu, 100g gula, 100g butter, 1 telur, 50g kismis, 1 sdt kayu manis', '1. Campur oat, tepung, dan kayu manis\n2. Kocok butter dan gula\n3. Tambahkan telur\n4. Masukkan campuran tepung\n5. Aduk rata\n6. Tambahkan kismis\n7. Bentuk bulat di loyang\n8. Panggang 180°C selama 15 menit', 'https://assets.marthastewart.com/styles/wmax-1500/d28/chewy_oatmeal_raisin_cookies/chewy_oatmeal_raisin_cookies_horiz.jpg?itok=5MhJH8Mj', 'Sedang', '1 jam'),
(21, 'Peanut Butter Cookies', 'Cookies', 'Oven, Mixer, Loyang datar, Garpu', '200g tepung terigu, 150g peanut butter, 100g gula, 1 telur, 50g butter, 1 sdt baking powder', '1. Campur tepung dan baking powder\n2. Kocok peanut butter, gula, dan butter\n3. Tambahkan telur\n4. Masukkan campuran tepung\n5. Aduk rata\n6. Bentuk bulat kecil\n7. Tekan dengan garpu untuk pola\n8. Panggang 180°C selama 12 menit\n9. Dinginkan sebelum disajikan', 'https://th.bing.com/th/id/R.25d9d38f4f32146dd73644bef18e1132?rik=T1xHnOvCBKSAoQ&riu=http%3a%2f%2fgarlicgirl.com%2fwp-content%2fuploads%2f2012%2f07%2fRoasted-Peanuts-Peanut-Butter-Cookies-f.jpg&ehk=vWJYuL9Bfn9hNKAdiBOiHyOA1GlTAhiO%2foRiRR4pJu0%3d&risl=1&pid=ImgRaw&r=0', 'Mudah', '45 menit'),
(22, 'Double Chocolate Cookies', 'Cookies', 'Oven, Mixer, Loyang datar, Mangkuk besar', '150g tepung terigu, 50g kakao bubuk, 100g gula, 100g butter, 1 telur, 100g dark chocolate, 1 sdt baking soda', '1. Campur tepung, kakao, dan baking soda\n2. Kocok butter dan gula\n3. Tambahkan telur\n4. Masukkan campuran tepung\n5. Aduk rata\n6. Tambahkan dark chocolate cincang\n7. Bentuk bulat kecil\n8. Panggang 180°C selama 12 menit\n9. Dinginkan 10 menit\n10. Sajikan', 'https://www.ifyougiveablondeakitchen.com/wp-content/uploads/2019/02/double-chocolate-chip-cookies-open-graph-image.jpg', 'Sedang', '1 jam'),
(23, 'Almond Cookies', 'Cookies', 'Oven, Mixer, Loyang datar, Mangkuk besar', '200g tepung terigu, 100g almond bubuk, 100g gula, 100g butter, 1 telur, 1 sdt baking powder', '1. Campur tepung, almond bubuk, dan baking powder\n2. Kocok butter dan gula\n3. Tambahkan telur\n4. Masukkan campuran tepung\n5. Aduk rata\n6. Bentuk bulat kecil\n7. Taburi almond slice di atasnya\n8. Panggang 180°C selama 15 menit', 'https://boondockingrecipes.com/wp-content/uploads/2025/01/29.-Chinese-Almond-Cookies-4.jpg', 'Sedang', '1 jam'),
(24, 'Apple Pie', 'Pie', 'Oven, Loyang pie, Rolling pin, Mangkuk besar', '300g tepung terigu, 150g butter, 50g gula, 4 apel, 50g brown sugar, 1 sdt kayu manis', '1. Campur tepung dan butter hingga berbutir\n2. Tambahkan gula dan sedikit air, bentuk adonan kulit\n3. Diamkan adonan 30 menit di kulkas\n4. Kupas dan iris apel\n5. Campur apel dengan brown sugar dan kayu manis\n6. Gilas adonan kulit, taruh di loyang\n7. Isi dengan apel\n8. Tutup dengan adonan kulit\n9. Panggang 180°C selama 45 menit', 'https://easykitchen.com/wp-content/uploads/2013/07/usapple_all-american-apple-pie.jpg', 'Sedang', '2 jam'),
(25, 'Pumpkin Pie', 'Pie', 'Oven, Loyang pie, Blender, Mangkuk besar', '300g labu kuning, 200g tepung terigu, 150g butter, 100g gula, 2 telur, 100ml krim, 1 sdt kayu manis', '1. Rebus labu hingga lunak\n2. Blender labu hingga halus\n3. Campur tepung dan butter untuk kulit\n4. Tambahkan gula dan air, bentuk adonan\n5. Diamkan 30 menit\n6. Gilas adonan, taruh di loyang\n7. Campur labu halus, telur, krim, gula, dan kayu manis\n8. Tuang ke kulit pie\n9. Panggang 180°C selama 50 menit\n10. Dinginkan sebelum disajikan', 'https://tse2.mm.bing.net/th/id/OIP.HMz8MXpIkrCi8Ou1srB_0gHaEK?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3', 'Sedang', '2.5 jam'),
(26, 'Lemon Meringue Pie', 'Pie', 'Oven, Loyang pie, Mixer, Mangkuk besar', '200g tepung terigu, 100g butter, 3 lemon, 150g gula, 3 telur, 100ml air', '1. Campur tepung dan butter untuk kulit\n2. Tambahkan gula dan air, bentuk adonan\n3. Gilas adonan, taruh di loyang\n4. Campur jus lemon, gula, dan kuning telur\n5. Masak hingga mengental\n6. Tuang ke kulit pie\n7. Kocok putih telur hingga kaku, taruh di atas\n8. Panggang 170°C selama 25 menit', 'https://www.recipetocook.co.uk/wp-content/uploads/2024/03/lemon-meringue-pie-recipe.jpg', 'Sulit', '2 jam'),
(27, 'Pecan Pie', 'Pie', 'Oven, Loyang pie, Mangkuk besar', '200g tepung terigu, 100g butter, 150g gula, 2 telur, 200g kacang pecan, 100ml sirup jagung', '1. Campur tepung dan butter untuk kulit\n2. Tambahkan gula dan air, bentuk adonan\n3. Gilas adonan, taruh di loyang\n4. Campur gula, telur, dan sirup jagung\n5. Aduk rata\n6. Tambahkan kacang pecan\n7. Tuang ke kulit pie\n8. Panggang 180°C selama 45 menit\n9. Dinginkan sebelum disajikan', 'https://insanelygoodrecipes.com/wp-content/uploads/2022/12/Sliced-Pecan-Pie-in-a-White-Plate.jpg', 'Sedang', '2 jam'),
(28, 'Chicken Pot Pie', 'Pie', 'Oven, Loyang pie, Panci, Mangkuk besar', '200g tepung terigu, 100g butter, 200g ayam rebus, 100g wortel, 100g kentang, 100ml susu, 1 sdt garam', '1. Campur tepung dan butter untuk kulit\n2. Tambahkan air, bentuk adonan\n3. Gilas adonan, taruh di loyang\n4. Potong ayam, wortel, dan kentang\n5. Masak dengan susu dan garam hingga kental\n6. Tuang isi ke kulit pie\n7. Tutup dengan adonan kulit\n8. Panggang 180°C selama 40 menit\n9. Dinginkan 10 menit\n10. Sajikan hangat', 'https://chocolatewithgrace.com/wp-content/uploads/2023/02/Chicken-Pot-Pie-with-Biscuits-CWG-12-1-of-1-scaled.jpg', 'Sulit', '2.5 jam'),
(29, 'Croissant', 'Pastry', 'Oven, Rolling pin, Loyang datar, Mangkuk besar', '500g tepung terigu, 300g butter, 200ml susu, 50g gula, 7g ragi, 1 telur', '1. Campur tepung, gula, dan ragi\n2. Tambahkan susu hangat, aduk rata\n3. Diamkan 30 menit\n4. Gilas adonan, taruh butter di tengah\n5. Lipat dan gilas berulang kali\n6. Diamkan 1 jam di kulkas\n7. Gilas dan potong segitiga\n8. Gulung jadi bentuk croissant\n9. Panggang 190°C selama 20 menit\n10. Sajikan hangat', 'https://wallpaperaccess.com/full/1694967.jpg', 'Sulit', '4 jam'),
(30, 'Danish Pastry', 'Pastry', 'Oven, Rolling pin, Loyang datar, Mangkuk besar', '400g tepung terigu, 200g butter, 100ml susu, 50g gula, 7g ragi, selai buah', '1. Campur tepung, gula, dan ragi\n2. Tambahkan susu hangat\n3. Diamkan 30 menit\n4. Gilas adonan, taruh butter di tengah\n5. Lipat dan gilas berulang kali\n6. Diamkan 1 jam\n7. Bentuk sesuai selera, isi selai\n8. Panggang 190°C selama 20 menit\n9. Sajikan', 'https://i.ytimg.com/vi/8zW2lnf23-Y/maxresdefault.jpg', 'Sulit', '3 jam'),
(31, 'Puff Pastry', 'Pastry', 'Oven, Rolling pin, Loyang datar, Mangkuk besar', '500g tepung terigu, 300g butter, 200ml air, 1 sdt garam', '1. Campur tepung dan garam\n2. Tambahkan air, aduk rata\n3. Gilas adonan, taruh butter di tengah\n4. Lipat dan gilas berulang kali\n5. Diamkan 30 menit di kulkas\n6. Gilas tipis\n7. Potong sesuai kebutuhan\n8. Panggang 200°C hingga mengembang', 'https://www.spatuladesserts.com/wp-content/uploads/2024/09/Apple-Roses-with-Puff-Pastry.jpg', 'Sulit', '3 jam'),
(32, 'Strudel', 'Pastry', 'Oven, Rolling pin, Loyang datar, Mangkuk besar', '300g tepung, 100g butter, 2 apel, 50g gula, 50g kismis, 1 sdt kayu manis', '1. Campur tepung dan butter\n2. Tambahkan air, bentuk adonan tipis\n3. Gilas adonan hingga tipis\n4. Kupas dan iris apel\n5. Campur apel dengan gula, kismis, dan kayu manis\n6. Taruh isi di atas adonan\n7. Gulung adonan\n8. Letakkan di loyang\n9. Panggang 180°C selama 40 menit\n10. Sajikan hangat', 'https://staticcookist.akamaized.net/wp-content/uploads/sites/22/2023/04/pear-strudel-1200x675.jpeg', 'Sedang', '2.5 jam'),
(33, 'Fruit Tart', 'Tart', 'Oven, Loyang tart, Mixer, Mangkuk besar', '200g tepung terigu, 100g butter, 50g gula, 1 telur, 200ml custard, buah segar', '1. Campur tepung, gula, dan butter\n2. Tambahkan telur, aduk rata\n3. Diamkan adonan 30 menit di kulkas\n4. Gilas adonan, taruh di loyang tart\n5. Panggang 180°C selama 20 menit\n6. Dinginkan kulit tart\n7. Isi dengan custard\n8. Susun buah segar di atasnya\n9. Sajikan dingin', 'https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/83E6B29B-4BDC-4D26-AAD7-2DEE59AAB83E/Derivates/24abe265-d49f-4490-88be-b31ea5d18afa.jpg', 'Sedang', '1.5 jam'),
(34, 'Chocolate Tart', 'Tart', 'Oven, Loyang tart, Mangkuk besar', '200g tepung terigu, 100g butter, 50g gula, 1 telur, 200g cokelat leleh, 100ml krim', '1. Campur tepung, gula, dan butter\n2. Tambahkan telur, aduk rata\n3. Diamkan adonan 30 menit\n4. Gilas adonan, taruh di loyang tart\n5. Panggang 180°C selama 20 menit\n6. Dinginkan kulit tart\n7. Isi dengan cokelat leleh dan krim\n8. Sajikan dingin', 'https://tse4.mm.bing.net/th/id/OIP.oK0Mf4Ezz30fnZsHlbiUGgHaEK?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3', 'Sedang', '2 jam'),
(35, 'Lemon Tart', 'Tart', 'Oven, Loyang tart, Mangkuk besar', '200g tepung terigu, 100g butter, 50g gula, 1 telur, 3 lemon, 100g gula tambahan', '1. Campur tepung, gula, dan butter\n2. Tambahkan telur, aduk rata\n3. Diamkan adonan 30 menit\n4. Gilas adonan, taruh di loyang tart\n5. Panggang 180°C selama 20 menit\n6. Campur jus lemon dan gula\n7. Masak hingga mengental\n8. Tuang ke kulit tart\n9. Sajikan dingin', 'https://tse1.mm.bing.net/th/id/OIP.qmh2vbsIDgdFbPNSOLl3pAHaEO?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3', 'Sedang', '2 jam'),
(36, 'Custard Tart', 'Tart', 'Oven, Loyang tart, Mixer, Mangkuk besar', '200g tepung terigu, 100g butter, 50g gula, 1 telur, 300ml susu, 2 telur tambahan, 50g gula', '1. Campur tepung, gula, dan butter\n2. Tambahkan telur, aduk rata\n3. Diamkan adonan 30 menit\n4. Gilas adonan, taruh di loyang tart\n5. Panggang 180°C selama 20 menit\n6. Campur susu, telur, dan gula\n7. Kocok hingga rata\n8. Tuang ke kulit tart\n9. Panggang 160°C selama 30 menit\n10. Sajikan dingin', 'https://img.taste.com.au/x-XQcESh/taste/2016/11/baked-custard-tart-42028-1.jpeg', 'Sulit', '2.5 jam'),
(37, 'Savory Tart', 'Tart', 'Oven, Loyang tart, Mangkuk besar', '200g tepung terigu, 100g butter, 50g gula, 1 telur, 100g bayam, 100g keju, 100ml krim', '1. Campur tepung, gula, dan butter\n2. Tambahkan telur, aduk rata\n3. Diamkan adonan 30 menit\n4. Gilas adonan, taruh di loyang tart\n5. Panggang 180°C selama 20 menit\n6. Tumis bayam dan campur dengan krim\n7. Tuang ke kulit tart\n8. Taburi keju dan panggang lagi 15 menit', 'https://images.sbs.com.au/55/9b/bdff7faa476badfbbfa11a08fe00/rx30-recipe-louistikram-tartlets-creditjiwonkim-tcus7-3.jpg?imwidth=960', 'Sedang', '2 jam'),
(38, 'Blueberry Muffin', 'Muffin', 'Oven, Loyang muffin, Mixer, Mangkuk besar', '200g tepung terigu, 100g gula, 100g butter, 2 telur, 100ml susu, 100g blueberry, 1 sdt baking powder', '1. Campur tepung dan baking powder\n2. Kocok butter dan gula hingga lembut\n3. Tambahkan telur satu per satu\n4. Masukkan susu\n5. Tambahkan campuran tepung\n6. Aduk rata\n7. Masukkan blueberry\n8. Tuang ke loyang muffin\n9. Panggang 180°C selama 20 menit', 'https://static01.nyt.com/images/2015/05/20/dining/20HIT_BLUEBERRYMUFFINS/20HIT_BLUEBERRYMUFFINS-superJumbo.jpg', 'Mudah', '1 jam'),
(39, 'Banana Muffin', 'Muffin', 'Oven, Loyang muffin, Mangkuk besar', '200g tepung terigu, 100g gula, 2 pisang matang, 1 telur, 50g butter, 1 sdt baking powder', '1. Haluskan pisang matang\n2. Campur tepung dan baking powder\n3. Kocok telur dan gula\n4. Tambahkan butter cair\n5. Masukkan pisang halus\n6. Aduk rata\n7. Tuang ke loyang muffin\n8. Panggang 180°C selama 25 menit', 'https://cdn.cdnparenting.com/articles/2018/11/04125526/banana-muffins-recipe_236127874-1024x700.webp', 'Mudah', '1 jam'),
(40, 'Chocolate Muffin', 'Muffin', 'Oven, Loyang muffin, Mixer, Mangkuk besar', '200g tepung terigu, 50g kakao bubuk, 100g gula, 100g butter, 2 telur, 100ml susu, 1 sdt baking powder', '1. Campur tepung, kakao, dan baking powder\n2. Kocok butter dan gula\n3. Tambahkan telur satu per satu\n4. Masukkan susu\n5. Tambahkan campuran tepung\n6. Aduk rata\n7. Tuang ke loyang muffin\n8. Panggang 180°C selama 20 menit\n9. Dinginkan 10 menit\n10. Sajikan', 'https://theviewfromgreatisland.com/wp-content/uploads/2021/01/chocolate-muffins-17.jpg', 'Sedang', '1.5 jam'),
(41, 'Classic Scone', 'Scone', 'Oven, Loyang datar, Mangkuk besar, Rolling pin', '250g tepung terigu, 50g gula, 50g butter, 150ml susu, 1 telur, 1 sdt baking powder', '1. Campur tepung, gula, dan baking powder\n2. Masukkan butter dingin, aduk hingga berbutir\n3. Tambahkan susu dan telur\n4. Aduk cepat hingga adonan menyatu\n5. Gilas adonan setebal 2 cm\n6. Potong bulat dengan cutter\n7. Taruh di loyang\n8. Panggang 200°C selama 15 menit', 'https://tse1.mm.bing.net/th/id/OIP.O8S7bQqSJUJD6oISzPwn8wHaEt?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3', 'Mudah', '1 jam'),
(42, 'Cheese Scone', 'Scone', 'Oven, Loyang datar, Mangkuk besar, Parutan', '250g tepung terigu, 50g butter, 100g keju parut, 150ml susu, 1 telur, 1 sdt baking powder', '1. Campur tepung dan baking powder\n2. Masukkan butter dingin, aduk hingga berbutir\n3. Tambahkan keju parut\n4. Masukkan susu dan telur\n5. Aduk cepat hingga adonan menyatu\n6. Gilas adonan setebal 2 cm\n7. Potong bulat dengan cutter\n8. Taruh di loyang\n9. Panggang 200°C selama 15 menit', 'https://www.pinkwhen.com/wp-content/uploads/2024/05/The_Best_Cheese_Scones.jpg', 'Sedang', '1 jam'),
(43, 'Raisin Scone', 'Scone', 'Oven, Loyang datar, Mangkuk besar', '250g tepung terigu, 50g butter, 50g gula, 100g kismis, 150ml susu, 1 telur, 1 sdt baking powder', '1. Campur tepung, gula, dan baking powder\n2. Masukkan butter dingin, aduk hingga berbutir\n3. Tambahkan kismis\n4. Masukkan susu dan telur\n5. Aduk cepat hingga adonan menyatu\n6. Gilas adonan setebal 2 cm\n7. Potong bulat dengan cutter\n8. Taruh di loyang\n9. Panggang 200°C selama 15 menit\n10. Dinginkan sebelum disajikan', 'https://tse2.mm.bing.net/th/id/OIP.v12XOvoFCYbKoWxbYAgcBgHaE8?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3', 'Sedang', '1 jam'),
(44, 'Quiche Lorraine', 'Quiche', 'Oven, Loyang pie, Mangkuk besar, Wisk', '200g tepung terigu, 100g butter, 2 telur, 200ml krim, 100g bacon, 100g keju', '1. Campur tepung dan butter untuk kulit\n2. Tambahkan air, bentuk adonan\n3. Gilas adonan, taruh di loyang\n4. Panggang kulit 180°C selama 15 menit\n5. Tumis bacon hingga matang\n6. Campur telur, krim, dan keju\n7. Tambahkan bacon ke campuran\n8. Tuang ke kulit pie\n9. Panggang 180°C selama 30 menit', 'https://tse2.mm.bing.net/th/id/OIP.e9HB2FyHT4CEY0lXoI0DEAHaFj?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3', 'Sedang', '2 jam'),
(45, 'Spinach Quiche', 'Quiche', 'Oven, Loyang pie, Mangkuk besar', '200g tepung terigu, 100g butter, 2 telur, 200ml krim, 150g bayam, 100g keju', '1. Campur tepung dan butter untuk kulit\n2. Tambahkan air, bentuk adonan\n3. Gilas adonan, taruh di loyang\n4. Panggang kulit 180°C selama 15 menit\n5. Tumis bayam sebentar\n6. Campur telur, krim, dan keju\n7. Tambahkan bayam ke campuran\n8. Tuang ke kulit pie dan panggang 30 menit', 'https://tse2.mm.bing.net/th/id/OIP.qpHX01OtI0K92hQ_hCop4wHaE8?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3', 'Sedang', '2 jam'),
(46, 'Mushroom Quiche', 'Quiche', 'Oven, Loyang pie, Mangkuk besar, Wisk', '200g tepung terigu, 100g butter, 2 telur, 200ml krim, 150g jamur, 100g keju', '1. Campur tepung dan butter untuk kulit\n2. Tambahkan air, bentuk adonan\n3. Gilas adonan, taruh di loyang\n4. Panggang kulit 180°C selama 15 menit\n5. Tumis jamur hingga matang\n6. Campur telur, krim, dan keju\n7. Tambahkan jamur ke campuran\n8. Tuang ke kulit pie\n9. Panggang 180°C selama 30 menit', 'https://th.bing.com/th/id/R.0c9a2c806e14e761c0b6b912d523fa3b?rik=wjZaHrqEY%2bh5Uw&riu=http%3a%2f%2ffoodstylist.co.za%2fwp-content%2fuploads%2f2020%2f08%2fQuicheF.jpg&ehk=LLgsHDlkA%2bVC%2b3fMOCkGHZmhYVUj2rYkJY%2fIqOuGATQ%3d&risl=&pid=ImgRaw&r=0', 'Sedang', '2 jam'),
(47, 'Broccoli Quiche', 'Quiche', 'Oven, Loyang pie, Mangkuk besar', '200g tepung terigu, 100g butter, 2 telur, 200ml krim, 150g brokoli, 100g keju', '1. Campur tepung dan butter untuk kulit\n2. Tambahkan air, bentuk adonan\n3. Gilas adonan, taruh di loyang\n4. Panggang kulit 180°C selama 15 menit\n5. Rebus brokoli sebentar\n6. Campur telur, krim, dan keju\n7. Tambahkan brokoli ke campuran\n8. Tuang ke kulit pie\n9. Panggang 180°C selama 30 menit\n10. Dinginkan 10 menit sebelum disajikan', 'https://tse3.mm.bing.net/th/id/OIP.iUzmAKalPgkrvYyxlAhCcAHaE8?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3', 'Sedang', '2 jam');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `recipes`
--
ALTER TABLE `recipes`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `recipes`
--
ALTER TABLE `recipes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=49;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
